---
title: "EDS212_Day2_Session2"
---

```{r}
library(tidyverse)
library(palmerpenguins)
```

## Plotting functions in ggplot2

```{r}
#write a function
fx <- function(x) {
  3 * x ^ 2 + 4
}
# ggplot likes a data frame, we made a data frame with 1 and 100 in the x column, c allows us to make a vector aka combine 1 and 100, we told what data to use, 
ggplot(data.frame(x = c(1, 100)), aes(x = x)) + 
#function to use is fx
  geom_function(fun = fx)

```

## Partial Derivative Example

```{r}
#making a derivative
fxyz = expression(2 * x * y + 3 * (x ^ 2) *(z ^ 3))
#making the partial derivative with respect to y
dfdy = D(fxyz, 'y')
#show me the derivative with respect to y
dfdy
```

## Penguins Plot

```{r}
#need to know data source, variables to use, and type of point
ggplot((data = penguins), aes(x = flipper_length_mm, y = body_mass_g)) +
         geom_point() + 
#added x,y, and title labels
  labs(x = "Flipper length (mm)",
       y = "Body Mass (g)",
       title = "Palmer Penguins body dimensions")

```

```{r}
#need to know data source, variables to use, and type of point
#created a distinction by species for color
ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g, color = species))  +
         geom_point() + 
#added x,y, and title labels
  labs(x = "Flipper length (mm)",
       y = "Body Mass (g)",
       title = "Palmer Penguins body dimensions")

theme_minimal()

```

```{r}
#need to know data source, variables to use, and type of point

ggplot(data = penguins, aes(x = flipper_length_mm, y = body_mass_g,))  +
         geom_point( color = 'green') + 
#added x,y, and title labels
  labs(x = "Flipper length (mm)",
       y = "Body Mass (g)",
       title = "Palmer Penguins body dimensions")

theme_minimal()
```
